### ISSUE TITLE
Country Name needs to pull from destination location

### ISSUE THREAD

**Issue by cmatsuta** [edonohue8/project-1#35]
Currently country name is not pull from destination location. Depends on the alphabetical order of origin and destination country, advisory results returns as origin county. 

It's set to array [1], but we need to some how look up destination location to guide to correct array. 
countryName = (response.Places[1].CountryName);

![image](https://user-images.githubusercontent.com/53271361/93691648-e5795e00-fa9c-11ea-8359-a51bd03689b3.png)

![image](https://user-images.githubusercontent.com/53271361/93691654-004bd280-fa9d-11ea-96f0-77a7f08c9332.png)

**Comment by cmatsuta** [comment]
If you have some idea how to fix this issue, please advise.

**Comment by edonohue8** [comment]
If statement for 'no response' contained a return statement that caused issue, but resolved now.  Good job team!
